# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hello_world-desktop' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for hello_world-desktop

end

target 'hello_world-mobile' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  # Pods for FacebookIOSLogin
  pod 'FBSDKCoreKit','11.1.0'
  pod 'FBSDKLoginKit','11.1.0'
  pod 'FBSDKShareKit','11.1.0'
  # Pods for hello_world-mobile

end
